export const ImagesMockup = [
  {
    id: 1,
    title: "Playa tropical",
    description: "Hermosa playa tropical con aguas cristalinas y palmeras.",
    category: "Naturaleza",
    subcategory: "Playas",
    etiquetas: "#playa #tropical #naturaleza",
    image_url: "https://images.pexels.com/photos/1049298/pexels-photo-1049298.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 2,
    title: "Montañas majestuosas",
    description:
      "Impresionantes montañas cubiertas de nieve bajo un cielo azul claro.",
    category: "Naturaleza",
    subcategory: "Montañas",
    etiquetas: "#montañas #nieve #paisaje",
    image_url: "https://images.pexels.com/photos/18353689/pexels-photo-18353689/free-photo-of-montanas-punto-de-referencia-arboles-estados-unidos.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 3,
    title: "Ciudad nocturna",
    description: "Vista panorámica de una ciudad iluminada por la noche.",
    category: "Ciudades",
    subcategory: "Nocturnas",
    etiquetas: "#ciudad #noche #luces",
    image_url: "https://images.pexels.com/photos/115553/pexels-photo-115553.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 4,
    title: "Cascada en la selva",
    description:
      "Una impresionante cascada fluyendo en medio de la selva exuberante.",
    category: "Naturaleza",
    subcategory: "Cascadas",
    etiquetas: "#cascada #selva #naturaleza",
    image_url: "https://images.pexels.com/photos/464327/pexels-photo-464327.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 5,
    title: "Arquitectura urbana",
    description:
      "Edificios modernos y arquitectura contemporánea en una ciudad.",
    category: "Arquitectura",
    subcategory: "Moderna",
    etiquetas: "#arquitectura #ciudad #moderna",
    image_url: "https://images.pexels.com/photos/12494795/pexels-photo-12494795.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 6,
    title: "Atardecer en la playa",
    description:
      "Un hermoso atardecer en la playa con colores cálidos en el cielo.",
    category: "Naturaleza",
    subcategory: "Playas",
    etiquetas: "#atardecer #playa #naturaleza",
    image_url: "https://images.pexels.com/photos/1136571/pexels-photo-1136571.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 7,
    title: "Montañas al amanecer",
    description: "Las montañas bañadas por la luz dorada del amanecer.",
    category: "Naturaleza",
    subcategory: "Montañas",
    etiquetas: "#amanecer #montañas #naturaleza",
    image_url: "https://images.pexels.com/photos/18353689/pexels-photo-18353689/free-photo-of-montanas-punto-de-referencia-arboles-estados-unidos.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 8,
    title: "Ciudad moderna",
    description: "Una vista panorámica de una ciudad con rascacielos modernos.",
    category: "Ciudades",
    subcategory: "Moderna",
    etiquetas: "#ciudad #moderna #rascacielos",
    image_url: "https://images.pexels.com/photos/5031139/pexels-photo-5031139.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 9,
    title: "Lago en el bosque",
    description: "Un lago tranquilo rodeado de árboles en un bosque sereno.",
    category: "Naturaleza",
    subcategory: "Bosques",
    etiquetas: "#lago #bosque #naturaleza",
    image_url: "https://images.pexels.com/photos/2649403/pexels-photo-2649403.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 10,
    title: "Cielo estrellado",
    description:
      "Un cielo nocturno lleno de estrellas brillantes y la Vía Láctea.",
    category: "Naturaleza",
    subcategory: "Nocturnas",
    etiquetas: "#cielo #estrellas #noche",
    image_url: "https://images.pexels.com/photos/2646380/pexels-photo-2646380.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 11,
    title: "Playa al atardecer",
    description:
      "Una hermosa playa con un atardecer espectacular en el horizonte.",
    category: "Naturaleza",
    subcategory: "Playas",
    etiquetas: "#playa #atardecer #naturaleza",
    image_url: "https://images.pexels.com/photos/1136571/pexels-photo-1136571.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 12,
    title: "Montañas cubiertas de niebla",
    description: "Montañas en la distancia cubiertas de niebla misteriosa.",
    category: "Naturaleza",
    subcategory: "Montañas",
    etiquetas: "#montañas #niebla #naturaleza",
    image_url: "https://images.pexels.com/photos/18353689/pexels-photo-18353689/free-photo-of-montanas-punto-de-referencia-arboles-estados-unidos.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 13,
    title: "Avenida urbana",
    description: "Una avenida arbolada en una ciudad vibrante.",
    category: "Ciudades",
    subcategory: "Urbanas",
    etiquetas: "#avenida #ciudad #urbanismo",
    image_url: "https://images.pexels.com/photos/5031139/pexels-photo-5031139.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 14,
    title: "Cascada en el bosque",
    description: "Una cascada serena fluyendo a través de un denso bosque.",
    category: "Naturaleza",
    subcategory: "Cascadas",
    etiquetas: "#cascada #bosque #naturaleza",
    image_url: "https://images.pexels.com/photos/464327/pexels-photo-464327.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 15,
    title: "Vista panorámica de la ciudad",
    description: "Una vista impresionante de una ciudad desde las alturas.",
    category: "Ciudades",
    subcategory: "Panorámicas",
    etiquetas: "#ciudad #vista #panorámica",
    image_url:
      "https://images.pexels.com/photos/1563256/pexels-photo-1563256.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
];
