export const location = {
  provinces: [
    {
      name: "San José",
      cantons: [
        {
          name: "San José",
          districts: [
            { name: "Carmen", metropolitanArea: true },
            { name: "Merced", metropolitanArea: true },
            { name: "Hospital", metropolitanArea: true },
            { name: "Catedral", metropolitanArea: true },
            { name: "Zapote", metropolitanArea: true },
            { name: "San Francisco de Dos Ríos", metropolitanArea: true },
            { name: "Uruca", metropolitanArea: true },
            { name: "Mata Redonda", metropolitanArea: true },
            { name: "Pavas", metropolitanArea: true },
            { name: "Hatillo", metropolitanArea: true },
            { name: "San Sebastián", metropolitanArea: true },
          ],
        },
        {
          name: "Escazú",
          districts: [
            { name: "Escazú", metropolitanArea: true },
            { name: "San Antonio", metropolitanArea: true },
            { name: "San Rafael", metropolitanArea: true },
          ],
        },
        {
          name: "Desamparados",
          districts: [
            { name: "Desamparados", metropolitanArea: true },
            { name: "San Miguel", metropolitanArea: true },
            { name: "San Juan de Dios", metropolitanArea: true },
            { name: "San Rafael Arriba", metropolitanArea: true },
            { name: "San Antonio", metropolitanArea: true },
            { name: "Frailes", metropolitanArea: true },
            { name: "Patarrá", metropolitanArea: true },
            { name: "San Cristóbal", metropolitanArea: true },
            { name: "Rosario", metropolitanArea: true },
            { name: "Damas", metropolitanArea: true },
            { name: "San Rafael Abajo", metropolitanArea: true },
            { name: "Gravilias", metropolitanArea: true },
            { name: "Los Guido", metropolitanArea: true },
          ],
        },
        {
          name: "Puriscal",
          districts: [
            { name: "Santiago", metropolitanArea: false },
            { name: "Mercedes Sur", metropolitanArea: false },
            { name: "Barbacoas", metropolitanArea: false },
            { name: "Grifo Alto", metropolitanArea: false },
            { name: "San Rafael", metropolitanArea: false },
            { name: "Candelarita", metropolitanArea: false },
            { name: "Desamparaditos", metropolitanArea: false },
            { name: "San Antonio", metropolitanArea: false },
            { name: "Chires", metropolitanArea: false },
          ],
        },
        {
          name: "Tarrazú",
          districts: [
            { name: "San Marcos", metropolitanArea: false },
            { name: "San Lorenzo", metropolitanArea: false },
            { name: "San Carlos", metropolitanArea: false },
          ],
        },
        {
          name: "Aserrí",
          districts: [
            { name: "Aserrí", metropolitanArea: true },
            { name: "Tarbaca", metropolitanArea: false },
            { name: "Vuelta de Jorco", metropolitanArea: false },
            { name: "San Gabriel", metropolitanArea: false },
            { name: "Legua", metropolitanArea: false },
            { name: "Monterrey", metropolitanArea: false },
            { name: "Salitrillos", metropolitanArea: true },
          ],
        },
        {
          name: "Mora",
          districts: [
            { name: "Colón", metropolitanArea: true },
            { name: "Guayabo", metropolitanArea: false },
            { name: "Tabarcia", metropolitanArea: false },
            { name: "Piedras Negras", metropolitanArea: false },
            { name: "Picagres", metropolitanArea: true },
          ],
        },
        {
          name: "Goicoechea",
          districts: [
            { name: "Guadalupe", metropolitanArea: true },
            { name: "San Francisco", metropolitanArea: true },
            { name: "Calle Blancos", metropolitanArea: true },
            { name: "Mata de Plátano", metropolitanArea: true },
            { name: "Ipís", metropolitanArea: true },
            { name: "Rancho Redondo", metropolitanArea: true },
            { name: "Purral", metropolitanArea: true },
          ],
        },
        {
          name: "Santa Ana",
          districts: [
            { name: "Santa Ana", metropolitanArea: true },
            { name: "Salitral", metropolitanArea: true },
            { name: "Pozos", metropolitanArea: true },
            { name: "Uruca", metropolitanArea: true },
            { name: "Piedades", metropolitanArea: true },
            { name: "Brasil", metropolitanArea: true },
          ],
        },
        {
          name: "Alajuelita",
          districts: [
            { name: "Alajuelita", metropolitanArea: true },
            { name: "San Josecito", metropolitanArea: true },
            { name: "San Antonio", metropolitanArea: true },
            { name: "Concepción", metropolitanArea: true },
            { name: "San Felipe", metropolitanArea: true },
          ],
        },
        {
          name: "Vázquez de Coronado",
          districts: [
            { name: "San Isidro", metropolitanArea: true },
            { name: "San Rafael", metropolitanArea: true },
            { name: "Dulce Nombre de Jesús", metropolitanArea: false },
            { name: "Patalillo", metropolitanArea: true },
            { name: "Cascajal", metropolitanArea: false },
          ],
        },
        {
          name: "Acosta",
          districts: [
            { name: "San Ignacio", metropolitanArea: false },
            { name: "Guaitil", metropolitanArea: false },
            { name: "Palmichal", metropolitanArea: false },
            { name: "Cangrejal", metropolitanArea: false },
            { name: "Sabanillas", metropolitanArea: false },
          ],
        },
        {
          name: "Tibás",
          districts: [
            { name: "San Juan", metropolitanArea: true },
            { name: "Cinco Esquinas", metropolitanArea: true },
            { name: "Anselmo Llorente", metropolitanArea: true },
            { name: "León XIII", metropolitanArea: true },
            { name: "Colima", metropolitanArea: true },
          ],
        },
        {
          name: "Moravia",
          districts: [
            { name: "San Vicente", metropolitanArea: true },
            { name: "San Jerónimo", metropolitanArea: true },
            { name: "La Trinidad", metropolitanArea: true },
          ],
        },
        {
          name: "Montes de Oca",
          districts: [
            { name: "San Pedro", metropolitanArea: true },
            { name: "Sabanilla", metropolitanArea: true },
            { name: "Mercedes", metropolitanArea: true },
            { name: "San Rafael", metropolitanArea: true },
          ],
        },
        {
          name: "Turrubares",
          districts: [
            { name: "San Pablo", metropolitanArea: false },
            { name: "San Pedro", metropolitanArea: false },
            { name: "San Juan de Mata", metropolitanArea: false },
            { name: "San Luis", metropolitanArea: false },
            { name: "Carara", metropolitanArea: false },
          ],
        },
        {
          name: "Dota",
          districts: [
            { name: "Santa María", metropolitanArea: false },
            { name: "Jardín", metropolitanArea: false },
            { name: "Copey", metropolitanArea: false },
          ],
        },
        {
          name: "Curridabat",
          districts: [
            { name: "Curridabat", metropolitanArea: true },
            { name: "Granadilla", metropolitanArea: true },
            { name: "Sánchez", metropolitanArea: true },
            { name: "Tirrases", metropolitanArea: true },
          ],
        },
        {
          name: "Pérez Zeledón",
          districts: [
            { name: "San Isidro de El General", metropolitanArea: false },
            { name: "El General", metropolitanArea: false },
            { name: "Daniel Flores", metropolitanArea: false },
            { name: "Rivas", metropolitanArea: false },
            { name: "San Pedro", metropolitanArea: false },
            { name: "Platanares", metropolitanArea: false },
            { name: "Pejibaye", metropolitanArea: false },
            { name: "Cajón", metropolitanArea: false },
            { name: "Barú", metropolitanArea: false },
            { name: "Río Nuevo", metropolitanArea: false },
            { name: "Páramo", metropolitanArea: false },
          ],
        },
        {
          name: "León Cortés Castro",
          districts: [
            { name: "San Pablo", metropolitanArea: false },
            { name: "San Andrés", metropolitanArea: false },
            { name: "Llano Bonito", metropolitanArea: false },
            { name: "San Isidro", metropolitanArea: false },
            { name: "Santa Cruz", metropolitanArea: false },
            { name: "San Antonio", metropolitanArea: false },
          ],
        },
      ],
    },
    {
      name: "Alajuela",
      cantons: [
        {
          name: "Alajuela",
          districts: [
            { name: "Alajuela", metropolitanArea: true },
            { name: "San José", metropolitanArea: true },
            { name: "Carrizal", metropolitanArea: true },
            { name: "San Antonio", metropolitanArea: true },
            { name: "Guácima", metropolitanArea: true },
            { name: "San Isidro", metropolitanArea: true },
            { name: "Sabanilla", metropolitanArea: true },
            { name: "San Rafael", metropolitanArea: true },
            { name: "Río Segundo", metropolitanArea: true },
            { name: "Desamparados", metropolitanArea: true },
            { name: "Turrúcares", metropolitanArea: true },
            { name: "Tambor", metropolitanArea: true },
            { name: "Garita", metropolitanArea: true },
            { name: "Sarapiquí", metropolitanArea: true },
          ],
        },
        {
          name: "San Ramón",
          districts: [
            { name: "San Ramón", metropolitanArea: false },
            { name: "Santiago", metropolitanArea: false },
            { name: "San Juan", metropolitanArea: false },
            { name: "Piedades Norte", metropolitanArea: false },
            { name: "Piedades Sur", metropolitanArea: false },
            { name: "San Rafael", metropolitanArea: false },
            { name: "San Isidro", metropolitanArea: false },
            { name: "Ángeles", metropolitanArea: false },
            { name: "Alfaro", metropolitanArea: false },
            { name: "Volio", metropolitanArea: false },
            { name: "Concepción", metropolitanArea: false },
            { name: "Zapotal", metropolitanArea: false },
            { name: "Peñas Blancas", metropolitanArea: false },
          ],
        },
        {
          name: "Grecia",
          districts: [
            { name: "Grecia", metropolitanArea: false },
            { name: "San Isidro", metropolitanArea: false },
            { name: "San José", metropolitanArea: false },
            { name: "San Roque", metropolitanArea: false },
            { name: "Tacares", metropolitanArea: false },
            { name: "Puente de Piedra", metropolitanArea: false },
            { name: "Bolívar", metropolitanArea: false },
          ],
        },
        {
          name: "San Mateo",
          districts: [
            { name: "San Mateo", metropolitanArea: false },
            { name: "Desmonte", metropolitanArea: false },
            { name: "Jesús María", metropolitanArea: false },
          ],
        },
        {
          name: "Atenas",
          districts: [
            { name: "Atenas", metropolitanArea: true },
            { name: "Jesús", metropolitanArea: true },
            { name: "Mercedes", metropolitanArea: true },
            { name: "San Isidro", metropolitanArea: false },
            { name: "Concepción", metropolitanArea: true },
            { name: "San José", metropolitanArea: false },
            { name: "Santa Eulalia", metropolitanArea: false },
            { name: "Escobal", metropolitanArea: true },
          ],
        },
        {
          name: "Naranjo",
          districts: [
            { name: "Naranjo", metropolitanArea: false },
            { name: "San Miguel", metropolitanArea: false },
            { name: "San José", metropolitanArea: false },
            { name: "Cirrí Sur", metropolitanArea: false },
            { name: "San Jerónimo", metropolitanArea: false },
            { name: "San Juan", metropolitanArea: false },
            { name: "El Rosario", metropolitanArea: false },
            { name: "Palmitos", metropolitanArea: false },
          ],
        },
        {
          name: "Palmares",
          districts: [
            { name: "Palmares", metropolitanArea: false },
            { name: "Zaragoza", metropolitanArea: false },
            { name: "Buenos Aires", metropolitanArea: false },
            { name: "Santiago", metropolitanArea: false },
            { name: "Candelaria", metropolitanArea: false },
            { name: "Esquipulas", metropolitanArea: false },
            { name: "La Granja", metropolitanArea: false },
          ],
        },
        {
          name: "Poás",
          districts: [
            { name: "San Pedro", metropolitanArea: true },
            { name: "San Juan", metropolitanArea: true },
            { name: "San Rafael", metropolitanArea: true },
            { name: "Carrillos", metropolitanArea: true },
            { name: "Sabana Redonda", metropolitanArea: true },
          ],
        },
        {
          name: "Orotina",
          districts: [
            { name: "Orotina", metropolitanArea: false },
            { name: "El Mastate", metropolitanArea: false },
            { name: "Hacienda Vieja", metropolitanArea: false },
            { name: "Coyolar", metropolitanArea: false },
            { name: "La Ceiba", metropolitanArea: false },
          ],
        },
        {
          name: "San Carlos",
          districts: [
            { name: "Quesada", metropolitanArea: false },
            { name: "Florencia", metropolitanArea: false },
            { name: "Buenavista", metropolitanArea: false },
            { name: "Aguas Zarcas", metropolitanArea: false },
            { name: "Venecia", metropolitanArea: false },
            { name: "Pital", metropolitanArea: false },
            { name: "La Fortuna", metropolitanArea: false },
            { name: "La Tigra", metropolitanArea: false },
            { name: "La Palmera", metropolitanArea: false },
            { name: "Venado", metropolitanArea: false },
            { name: "Cutris", metropolitanArea: false },
            { name: "Monterrey", metropolitanArea: false },
            { name: "Pocosol", metropolitanArea: false },
          ],
        },
        {
          name: "Zarcero",
          districts: [
            { name: "Zarcero", metropolitanArea: false },
            { name: "Laguna", metropolitanArea: false },
            { name: "Tapesco", metropolitanArea: false },
            { name: "Guadalupe", metropolitanArea: false },
            { name: "Palmira", metropolitanArea: false },
            { name: "Zapote", metropolitanArea: false },
            { name: "Brisas", metropolitanArea: false },
          ],
        },
        {
          name: "Sarchí",
          districts: [
            { name: "Sarchí Norte", metropolitanArea: false },
            { name: "Sarchí Sur", metropolitanArea: false },
            { name: "Toro Amarillo", metropolitanArea: false },
            { name: "San Pedro", metropolitanArea: false },
            { name: "Rodríguez", metropolitanArea: false },
          ],
        },
        {
          name: "Upala",
          districts: [
            { name: "Upala", metropolitanArea: false },
            { name: "Aguas Claras", metropolitanArea: false },
            { name: "San José o Pizote", metropolitanArea: false },
            { name: "Bijagua", metropolitanArea: false },
            { name: "Delicias", metropolitanArea: false },
            { name: "Dos Ríos", metropolitanArea: false },
            { name: "Yolillal", metropolitanArea: false },
          ],
        },
        {
          name: "Los Chiles",
          districts: [
            { name: "Los Chiles", metropolitanArea: false },
            { name: "Caño Negro", metropolitanArea: false },
            { name: "El Amparo", metropolitanArea: false },
            { name: "San Jorge", metropolitanArea: false },
          ],
        },
        {
          name: "Guatuso",
          districts: [
            { name: "San Rafael", metropolitanArea: false },
            { name: "Buenavista", metropolitanArea: false },
            { name: "Cote", metropolitanArea: false },
            { name: "Katira", metropolitanArea: false },
          ],
        },
        {
          name: "Río Cuarto",
          districts: [{ name: "Río Cuarto", metropolitanArea: false }],
        },
      ],
    },
    {
      name: "Cartago",
      cantons: [
        {
          name: "Cartago",
          districts: [
            { name: "Oriental", metropolitanArea: true },
            { name: "Occidental", metropolitanArea: true },
            { name: "Carmen", metropolitanArea: true },
            { name: "San Nicolás", metropolitanArea: true },
            { name: "Aguacaliente o San Francisco", metropolitanArea: true },
            { name: "Guadalupe o Arenilla", metropolitanArea: true },
            { name: "Corralillo", metropolitanArea: true },
            { name: "Tierra Blanca", metropolitanArea: true },
            { name: "Dulce Nombre", metropolitanArea: true },
            { name: "Llano Grande", metropolitanArea: true },
            { name: "Quebradilla", metropolitanArea: true },
          ],
        },
        {
          name: "Paraíso",
          districts: [
            { name: "Paraíso", metropolitanArea: true },
            { name: "Santiago", metropolitanArea: true },
            { name: "Orosi", metropolitanArea: true },
            { name: "Cachí", metropolitanArea: true },
            { name: "Llanos de Santa Lucía", metropolitanArea: true },
          ],
        },
        {
          name: "La Unión",
          districts: [
            { name: "Tres Ríos", metropolitanArea: true },
            { name: "San Diego", metropolitanArea: true },
            { name: "San Juan", metropolitanArea: true },
            { name: "San Rafael", metropolitanArea: true },
            { name: "Concepción", metropolitanArea: true },
            { name: "Dulce Nombre", metropolitanArea: true },
            { name: "San Ramón", metropolitanArea: true },
            { name: "Río Azul", metropolitanArea: true },
          ],
        },
        {
          name: "Jiménez",
          districts: [
            { name: "Juan Viñas", metropolitanArea: false },
            { name: "Tucurrique", metropolitanArea: false },
            { name: "Pejibaye", metropolitanArea: false },
          ],
        },
        {
          name: "Turrialba",
          districts: [
            { name: "Turrialba", metropolitanArea: false },
            { name: "La Suiza", metropolitanArea: false },
            { name: "Peralta", metropolitanArea: false },
            { name: "Santa Cruz", metropolitanArea: false },
            { name: "Santa Teresita", metropolitanArea: false },
            { name: "Pavones", metropolitanArea: false },
            { name: "Tuis", metropolitanArea: false },
            { name: "Tayutic", metropolitanArea: false },
            { name: "Santa Rosa", metropolitanArea: false },
            { name: "Tres Equis", metropolitanArea: false },
            { name: "La Isabel", metropolitanArea: false },
            { name: "Chirripó", metropolitanArea: false },
          ],
        },
        {
          name: "Alvarado",
          districts: [
            { name: "Pacayas", metropolitanArea: true },
            { name: "Cervantes", metropolitanArea: true },
            { name: "Capellades", metropolitanArea: true },
          ],
        },
        {
          name: "Oreamuno",
          districts: [
            { name: "San Rafael", metropolitanArea: true },
            { name: "Cot", metropolitanArea: true },
            { name: "Potrero Cerrado", metropolitanArea: true },
            { name: "Cipreses", metropolitanArea: true },
            { name: "Santa Rosa", metropolitanArea: true },
          ],
        },
        {
          name: "El Guarco",
          districts: [
            { name: "El Tejar", metropolitanArea: true },
            { name: "San Isidro", metropolitanArea: true },
            { name: "Tobosi", metropolitanArea: true },
            { name: "Patio de Agua", metropolitanArea: false },
          ],
        },
      ],
    },
    {
      name: "Heredia",
      cantons: [
        {
          name: "Heredia",
          districts: [
            { name: "Heredia", metropolitanArea: true },
            { name: "Mercedes", metropolitanArea: true },
            { name: "San Francisco", metropolitanArea: true },
            { name: "Ulloa", metropolitanArea: true },
            { name: "Varablanca", metropolitanArea: false },
          ],
        },
        {
          name: "Barva",
          districts: [
            { name: "Barva", metropolitanArea: true },
            { name: "San Pedro", metropolitanArea: true },
            { name: "San Pablo", metropolitanArea: true },
            { name: "San Roque", metropolitanArea: true },
            { name: "Santa Lucía", metropolitanArea: true },
            { name: "San José de la Montaña", metropolitanArea: true },
          ],
        },
        {
          name: "Santo Domingo",
          districts: [
            { name: "Santo Domingo", metropolitanArea: true },
            { name: "San Vicente", metropolitanArea: true },
            { name: "San Miguel", metropolitanArea: true },
            { name: "Paracito", metropolitanArea: true },
            { name: "Santo Tomás", metropolitanArea: true },
            { name: "Santa Rosa", metropolitanArea: true },
            { name: "Tures", metropolitanArea: true },
            { name: "Pará", metropolitanArea: true },
          ],
        },
        {
          name: "Santa Bárbara",
          districts: [
            { name: "Santa Bárbara", metropolitanArea: true },
            { name: "San Pedro", metropolitanArea: true },
            { name: "San Juan", metropolitanArea: true },
            { name: "Jesús", metropolitanArea: true },
            { name: "Santo Domingo", metropolitanArea: true },
            { name: "Purabá", metropolitanArea: true },
          ],
        },
        {
          name: "San Rafael",
          districts: [
            { name: "San Rafael", metropolitanArea: true },
            { name: "San Josecito", metropolitanArea: true },
            { name: "Santiago", metropolitanArea: true },
            { name: "Ángeles", metropolitanArea: true },
            { name: "Concepción", metropolitanArea: true },
          ],
        },
        {
          name: "San Isidro",
          districts: [
            { name: "San Isidro", metropolitanArea: true },
            { name: "San José", metropolitanArea: true },
            { name: "Concepción", metropolitanArea: true },
            { name: "San Francisco", metropolitanArea: true },
          ],
        },
        {
          name: "Belén",
          districts: [
            { name: "San Antonio", metropolitanArea: true },
            { name: "La Ribera", metropolitanArea: true },
            { name: "La Asunción", metropolitanArea: true },
          ],
        },
        {
          name: "Flores",
          districts: [
            { name: "San Joaquín", metropolitanArea: true },
            { name: "Barrantes", metropolitanArea: true },
            { name: "Llorente", metropolitanArea: true },
          ],
        },
        {
          name: "San Pablo",
          districts: [
            { name: "San Pablo", metropolitanArea: true },
            { name: "Rincón de Sabanilla", metropolitanArea: true },
          ],
        },
        {
          name: "Sarapiquí",
          districts: [
            { name: "Puerto Viejo", metropolitanArea: false },
            { name: "La Virgen", metropolitanArea: false },
            { name: "Las Horquetas", metropolitanArea: false },
            { name: "Llanuras del Gaspar", metropolitanArea: false },
            { name: "Cureña", metropolitanArea: false },
          ],
        },
      ],
    },
    {
      name: "Guanacaste",
      cantons: [
        {
          name: "Liberia",
          districts: [
            { name: "Liberia", metropolitanArea: false },
            { name: "Cañas Dulces", metropolitanArea: false },
            { name: "Mayorga", metropolitanArea: false },
            { name: "Nacascolo", metropolitanArea: false },
            { name: "Curubandé", metropolitanArea: false },
          ],
        },
        {
          name: "Nicoya",
          districts: [
            { name: "Nicoya", metropolitanArea: false },
            { name: "Mansión", metropolitanArea: false },
            { name: "San Antonio", metropolitanArea: false },
            { name: "Quebrada Honda", metropolitanArea: false },
            { name: "Sámara", metropolitanArea: false },
            { name: "Nosara", metropolitanArea: false },
            { name: "Belén de Nosarita", metropolitanArea: false },
          ],
        },
        {
          name: "Santa Cruz",
          districts: [
            { name: "Santa Cruz", metropolitanArea: false },
            { name: "Bolsón", metropolitanArea: false },
            { name: "Veintisiete de Abril", metropolitanArea: false },
            { name: "Tempate", metropolitanArea: false },
            { name: "Cartagena", metropolitanArea: false },
            { name: "Cuajiniquil", metropolitanArea: false },
            { name: "Diriá", metropolitanArea: false },
            { name: "Cabo Velas", metropolitanArea: false },
            { name: "Tamarindo", metropolitanArea: false },
          ],
        },
        {
          name: "Bagaces",
          districts: [
            { name: "Bagaces", metropolitanArea: false },
            { name: "La Fortuna", metropolitanArea: false },
            { name: "Mogote", metropolitanArea: false },
            { name: "Río Naranjo", metropolitanArea: false },
          ],
        },
        {
          name: "Carrillo",
          districts: [
            { name: "Filadelfia", metropolitanArea: false },
            { name: "Palmira", metropolitanArea: false },
            { name: "Sardinal", metropolitanArea: false },
            { name: "Belén", metropolitanArea: false },
          ],
        },
        {
          name: "Cañas",
          districts: [
            { name: "Cañas", metropolitanArea: false },
            { name: "Palmira", metropolitanArea: false },
            { name: "San Miguel", metropolitanArea: false },
            { name: "Bebedero", metropolitanArea: false },
            { name: "Porozal", metropolitanArea: false },
          ],
        },
        {
          name: "Abangares",
          districts: [
            { name: "Las Juntas", metropolitanArea: false },
            { name: "Sierra", metropolitanArea: false },
            { name: "San Juan", metropolitanArea: false },
            { name: "Colorado", metropolitanArea: false },
          ],
        },
        {
          name: "Tilarán",
          districts: [
            { name: "Tilarán", metropolitanArea: false },
            { name: "Quebrada Grande", metropolitanArea: false },
            { name: "Tronadora", metropolitanArea: false },
            { name: "Santa Rosa", metropolitanArea: false },
            { name: "Líbano", metropolitanArea: false },
            { name: "Tierras Morenas", metropolitanArea: false },
            { name: "Arenal", metropolitanArea: false },
          ],
        },
        {
          name: "Nandayure",
          districts: [
            { name: "Carmona", metropolitanArea: false },
            { name: "Santa Rita", metropolitanArea: false },
            { name: "Zapotal", metropolitanArea: false },
            { name: "San Pablo", metropolitanArea: false },
            { name: "Porvenir", metropolitanArea: false },
            { name: "Bejuco", metropolitanArea: false },
          ],
        },
        {
          name: "La Cruz",
          districts: [
            { name: "La Cruz", metropolitanArea: false },
            { name: "Santa Cecilia", metropolitanArea: false },
            { name: "La Garita", metropolitanArea: false },
            { name: "Santa Elena", metropolitanArea: false },
          ],
        },
        {
          name: "Hojancha",
          districts: [
            { name: "Hojancha", metropolitanArea: false },
            { name: "Monte Romo", metropolitanArea: false },
            { name: "Puerto Carrillo", metropolitanArea: false },
            { name: "Huacas", metropolitanArea: false },
            { name: "Matambú", metropolitanArea: false },
          ],
        },
      ],
    },
    {
      name: "Puntarenas",
      cantons: [
        {
          name: "Puntarenas",
          districts: [
            { name: "Puntarenas", metropolitanArea: false },
            { name: "Pitahaya", metropolitanArea: false },
            { name: "Chomes", metropolitanArea: false },
            { name: "Lepanto", metropolitanArea: false },
            { name: "Paquera", metropolitanArea: false },
            { name: "Manzanillo", metropolitanArea: false },
            { name: "Guacimal", metropolitanArea: false },
            { name: "Barranca", metropolitanArea: false },
            { name: "Monte Verde", metropolitanArea: false },
            { name: "Isla Del Coco", metropolitanArea: false },
            { name: "Cóbano", metropolitanArea: false },
            { name: "Chacarita", metropolitanArea: false },
            { name: "Chira", metropolitanArea: false },
            { name: "Acapulco", metropolitanArea: false },
            { name: "El Roble", metropolitanArea: false },
            { name: "Arancibia", metropolitanArea: false },
          ],
        },
        {
          name: "Esparza",
          districts: [
            { name: "Espíritu Santo", metropolitanArea: false },
            { name: "San Juan Grande", metropolitanArea: false },
            { name: "Macacona", metropolitanArea: false },
            { name: "San Rafael", metropolitanArea: false },
            { name: "San Jerónimo", metropolitanArea: false },
          ],
        },
        {
          name: "Buenos Aires",
          districts: [
            { name: "Buenos Aires", metropolitanArea: false },
            { name: "Volcán", metropolitanArea: false },
            { name: "Potrero Grande", metropolitanArea: false },
            { name: "Boruca", metropolitanArea: false },
            { name: "Pilas", metropolitanArea: false },
            { name: "Colinas", metropolitanArea: false },
            { name: "Chánguena", metropolitanArea: false },
            { name: "Biolley", metropolitanArea: false },
            { name: "Brunka", metropolitanArea: false },
          ],
        },
        {
          name: "Montes de Oro",
          districts: [
            { name: "Miramar", metropolitanArea: false },
            { name: "La Unión", metropolitanArea: false },
            { name: "San Isidro", metropolitanArea: false },
          ],
        },
        {
          name: "Osa",
          districts: [
            { name: "Puerto Cortés", metropolitanArea: false },
            { name: "Palmar", metropolitanArea: false },
            { name: "Sierpe", metropolitanArea: false },
            { name: "Bahía Ballena", metropolitanArea: false },
            { name: "Piedras Blancas", metropolitanArea: false },
          ],
        },
        {
          name: "Quepos",
          districts: [
            { name: "Quepos", metropolitanArea: false },
            { name: "Savegre", metropolitanArea: false },
            { name: "Naranjito", metropolitanArea: false },
          ],
        },
        {
          name: "Golfito",
          districts: [
            { name: "Golfito", metropolitanArea: false },
            { name: "Puerto Jiménez", metropolitanArea: false },
            { name: "Guaycará", metropolitanArea: false },
            { name: "Pavón", metropolitanArea: false },
          ],
        },
        {
          name: "Coto Brus",
          districts: [
            { name: "San Vito", metropolitanArea: false },
            { name: "Sabalito", metropolitanArea: false },
            { name: "Aguabuena", metropolitanArea: false },
            { name: "Limoncito", metropolitanArea: false },
            { name: "Pittier", metropolitanArea: false },
          ],
        },
        {
          name: "Parrita",
          districts: [{ name: "Parrita", metropolitanArea: false }],
        },
        {
          name: "Corredores",
          districts: [
            { name: "Corredor", metropolitanArea: false },
            { name: "La Cuesta", metropolitanArea: false },
            { name: "Canoas", metropolitanArea: false },
            { name: "Laurel", metropolitanArea: false },
          ],
        },
        {
          name: "Garabito",
          districts: [
            { name: "Jacó", metropolitanArea: false },
            { name: "Tárcoles", metropolitanArea: false },
          ],
        },
      ],
    },
    {
      name: "Limón",
      cantons: [
        {
          name: "Limón",
          districts: [
            { name: "Limón", metropolitanArea: false },
            { name: "Valle La Estrella", metropolitanArea: false },
            { name: "Río Blanco", metropolitanArea: false },
            { name: "Matama", metropolitanArea: false },
          ],
        },
        {
          name: "Pococí",
          districts: [
            { name: "Guápiles", metropolitanArea: false },
            { name: "Jiménez", metropolitanArea: false },
            { name: "Rita", metropolitanArea: false },
            { name: "Roxana", metropolitanArea: false },
            { name: "Cariari", metropolitanArea: false },
            { name: "Colorado", metropolitanArea: false },
          ],
        },
        {
          name: "Siquirres",
          districts: [
            { name: "Siquirres", metropolitanArea: false },
            { name: "Pacuarito", metropolitanArea: false },
            { name: "Florida", metropolitanArea: false },
            { name: "Germania", metropolitanArea: false },
            { name: "El Cairo", metropolitanArea: false },
            { name: "Alegría", metropolitanArea: false },
          ],
        },
        {
          name: "Talamanca",
          districts: [
            { name: "Bratsi", metropolitanArea: false },
            { name: "Sixaola", metropolitanArea: false },
            { name: "Cahuita", metropolitanArea: false },
            { name: "Telire", metropolitanArea: false },
          ],
        },
        {
          name: "Matina",
          districts: [
            { name: "Matina", metropolitanArea: false },
            { name: "Batán", metropolitanArea: false },
            { name: "Carrandi", metropolitanArea: false },
          ],
        },
        {
          name: "Guácimo",
          districts: [
            { name: "Guácimo", metropolitanArea: false },
            { name: "Mercedes", metropolitanArea: false },
            { name: "Pocora", metropolitanArea: false },
            { name: "Río Jiménez", metropolitanArea: false },
            { name: "Duacarí", metropolitanArea: false },
          ],
        },
      ],
    },
  ],
};
